### ISSUE TITLE
Inconsistency in hub-dimensions between report and models

### ISSUE THREAD

**Issue by cgrindedtu** [IEAWindTask37/IEA-10.0-198-RWT#27]
Hi all,
There seems to be some inconsistencies between the report, the HAWC2 model and the Openfast model, in regards to the size of the hub. 

The report states that the hub-diameter is 4.6m and the total rotor diameter is 198.0m 
The hawc2 .htc file has the hub radius to being 2.80m, while the added hub-length to the shaft is 2.47m 
The openfast model has the HubRad=2.40m 

According to the figure on p. 123 of the report, the hub height is 2.47m, while the 2.8m is the hub length. 
So it could be that these two have just been swapped in the .htc file.
However, since the blade is 96.2m long in z, the total diameter only becomes 198.0m if the hub height is 2.8m. 
And the 4.6m hub diameter stated in the report, does not seem to fit any of the models. 

So something seems off. 
I have also spoken to @davidovitch who agrees that something seems inconsistent. 

Kind regards
Christian Grinderslev

**Comment by fzahle** [comment]
With reference to Figure 37, the correct "hub_height" is 2.8 m, same as for the DTU 10MW RWT (the naming is perhaps a bit unfortunate since we typically associate that with the height above ground).

In Table 9 on p 36, the "Hub diameter" listed there, should in fact be "Root diameter", which is indeed 4.6 m. Apart from reviewing the HAWC2 and OpenFAST models we should also update the yaml input, for which the hub_diameter (ie. "hub height in Fig 37) is also stated to be 4.6 m.
